### PR TITLE
Added JumpGame in C++ Greedy algorithm

### PR DESCRIPTION
**Pull request by Starkultra**
problem: Jump Game
problem Description: 
 Given an array of non-negative integers, you are initially positioned at the first index of the array.
Each element in the array represents your maximum jump length at that position.
Determine if you are able to reach the last index.

Example 1:
Input: nums = [2,3,1,1,4]
Output: true
Explanation: Jump 1 step from index 0 to 1, then 3 steps to the last index.

Example 2:
Input: nums = [3,2,1,0,4]
Output: false
Explanation: You will always arrive at index 3 no matter what. Its maximum jump length is 0, which makes it impossible to reach the last index.
 
Constraints:
1 <= nums.length <= 3 * 10^4
0 <= nums[i][j] <= 10^5

### CODE REVIEW

**Comment by Starkultra** [comment]
Added Jump Game in c++

**Comment by Starkultra** [comment]
Added Search_in_rotated_sorted_array.cpp

**Comment by Starkultra** [comment]
problem :Given an array of strings strs, group the anagrams together. You can return the answer in any order.

         An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.

 
INPUT: 
strs = ["eat","tea","tan","ate","nat","bat"]
OUTPUT: [["bat"],["nat","tan"],["ate","eat","tea"]]


Input: strs = [""]
Output: [[""]]


Sample input:
strs = ["a"]
Sample output: 
[["a"]]
 

Constraints:

1 <= strs.length <= 104
0 <= strs[i].length <= 100
strs[i] consists of lower-case English letters.

**Review by SidJain1412 — APPROVED** [review]
Great programs! Looks good to me, thanks for the contribution

**Pull request merged**
